-- carl:kind=ddl
-- The watering timer, and the phone it reaches (Phase 16; Phase 15 handoff
-- Section 3.2).
--
-- "Water Zone 1 for 60 minutes; ping me when it is done." Nothing on this
-- host can hold a connection open or run except from cron (hosting Section
-- 3), so a timer is a ROW with an end time, a cron that wakes every minute
-- and fires the rows whose time has come, and two ways of reaching a phone:
-- Web Push to the home-screen app, and the mail outbox as the fallback for
-- a phone that never installed it or whose subscription quietly died.
-- Granularity is therefore up to a minute late, which for a watering is
-- nothing.

-- One timer. Fired is a timestamp and not a flag because the cron claims a
-- row with a compare-and-swap on it (fired_at IS NULL), so two overlapping
-- runs -- a slow minute, a cron and its browser twin both pointed at the
-- same rows -- fire it once.
CREATE TABLE `water_timer` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id`         INT UNSIGNED NOT NULL,
  `garden_id`       INT UNSIGNED NOT NULL,
  -- NULL is the whole garden, exactly as the garden actions form allows.
  `water_zone_id`   INT UNSIGNED     NULL,
  `minutes`         SMALLINT UNSIGNED NOT NULL,
  `started_at`      DATETIME     NOT NULL,
  `ends_at`         DATETIME     NOT NULL,
  `fired_at`        DATETIME         NULL,
  `cancelled_at`    DATETIME         NULL,
  -- "Log the watering when it finishes": the cron writes the garden_event
  -- (and its fan-out to the zone's plants) itself, and the notification's
  -- tap just confirms. Off, the tap is the log form, prefilled.
  `log_when_done`   TINYINT(1)   NOT NULL DEFAULT 1,
  `logged_event_id` BIGINT UNSIGNED  NULL,
  -- How the person was reached: 'push', 'email', or 'none' when there was
  -- no subscription and no usable address. For the landing page and /status.
  `notified_via`    VARCHAR(16)      NULL,
  `fire_error`      VARCHAR(500)     NULL,
  `created_at`      DATETIME     NOT NULL,
  PRIMARY KEY (`id`),
  -- The cron's question: what is due and not yet fired.
  KEY `idx_timer_due` (`fired_at`, `cancelled_at`, `ends_at`),
  KEY `idx_timer_user` (`user_id`, `fired_at`),
  KEY `idx_timer_garden` (`garden_id`),
  KEY `idx_timer_zone` (`water_zone_id`),
  CONSTRAINT `fk_timer_user` FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_timer_garden` FOREIGN KEY (`garden_id`)
    REFERENCES `garden` (`id`) ON DELETE CASCADE,
  -- SET NULL: deleting a zone must not lose the record that a timer ran.
  CONSTRAINT `fk_timer_zone` FOREIGN KEY (`water_zone_id`)
    REFERENCES `water_zone` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- A browser that asked to be told. The endpoint is the push service's URL
-- for one browser on one origin and can run to several hundred characters,
-- so the unique key is on a hash of it. `failed_at` is set when the push
-- service says the subscription is gone (404 or 410); the row is kept so the
-- garden actions page can say "this phone stopped listening on <date>"
-- rather than silently offering to subscribe again.
CREATE TABLE `push_subscription` (
  `id`            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id`       INT UNSIGNED NOT NULL,
  `endpoint`      VARCHAR(1000) NOT NULL,
  `endpoint_hash` CHAR(64)     NOT NULL,
  -- The browser's P-256 public key and 16-byte auth secret, base64url as
  -- the browser hands them over (RFC 8291).
  `p256dh`        VARCHAR(120) NOT NULL,
  `auth`          VARCHAR(40)  NOT NULL,
  `user_agent`    VARCHAR(190) NOT NULL DEFAULT '',
  `created_at`    DATETIME     NOT NULL,
  `last_used_at`  DATETIME         NULL,
  `failed_at`     DATETIME         NULL,
  `fail_reason`   VARCHAR(200)     NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_push_endpoint` (`endpoint_hash`),
  KEY `idx_push_user` (`user_id`, `failed_at`),
  CONSTRAINT `fk_push_user` FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The VAPID key pair (RFC 8292): one per install, generated by Carl itself
-- at /setup because this account has no shell to run openssl in (hosting
-- Section 3). The public half goes to every browser that subscribes; a
-- changed pair invalidates every subscription, which is why there is one
-- row and it is never rewritten. Stored as the raw P-256 scalar and point,
-- base64url, the form the push service and the browser each want.
CREATE TABLE `push_key` (
  `id`          TINYINT UNSIGNED NOT NULL,
  `public_key`  VARCHAR(100) NOT NULL,
  `private_key` VARCHAR(60)  NOT NULL,
  `created_at`  DATETIME     NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
